import type { NextPage } from "next";
import Head from "next/head";
import HtmlText from "../components/HtmlText";
import { Comment } from "../server/router/hn";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const story = trpc.useQuery(["hn.story", { id: 32650432 }]);

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <p className="text-2xl text-gray-700">This stack uses:</p>
        {story.data?.children.map((child) => (
          <Comment key={child.id} {...child} />
        ))}
      </main>
    </>
  );
};

const Comment = ({
  id,
  created_at,
  author,
  text,
  points,
  children,
}: Comment) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{author}</h2>
      <HtmlText value={text} />

      <span>{points}</span>
    </section>
  );
};

export default Home;
